# Nome da aplicação
spring.application.name=todolist

# Configuração do banco H2 em memória
spring.datasource.url=jdbc:h2:mem:tododb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Mostra as queries SQL no console (bom pra aprender o que o JPA está fazendo)
spring.jpa.show-sql=true

# Cria/atualiza as tabelas automaticamente a partir das nossas classes Java
spring.jpa.hibernate.ddl-auto=update

# Habilita o console visual do H2 em http://localhost:8080/h2-console
spring.h2.console.enabled=true